### ISSUE TITLE
Compile it?

### ISSUE THREAD

**Issue by Resoluciones** [spikedboy/Guerrilla#1]
Hi! Great plugin!

Would it be possible to compile it against latest spigot/bukkit/paper?

Thank you!!!!!!!!!!!!!

**Comment by spikedboy** [comment]
I wrote it years ago, I plan on refactoring and releasing it taking into account the newest minecraft versions. But that will take me a while. 
Let me see if it is easy to just compile with the newest bukkit version.

**Comment by spikedboy** [comment]
Here you go:
https://github.com/spikedboy/Guerrilla/releases/tag/0.2

Let me know if all is right.
Cheers.

**Comment by Resoluciones** [comment]
Great I will install it!  I remember I used this plugin a lot years ago and it was really fun.

In case you are going to work on a new version, it would be more than great you can make it compatible with https://github.com/Scyntrus/FactionMobs as that plugin add lots of possibitlies or maybe the author of FactionMobs can make it compatible with yours (I don't know how those compatibilities are made).

We keep in touch!

Thanks and regards!

**Comment by spikedboy** [comment]
I have several other fixes to make, I've put them into issues here. The plugin is so old it still identifies players with usernames. There will be issuess if someone changes their names, or players have the same name.

I will be fixing them for fun this week, so if you're going to use it keep in mind these updates!

Glad to see this still used. Agree it was lots of fun back in the day! Man, I made this almost 9 years ago.

If you find anything or would like improvements open them here as issuess, I will consider them.
If you put this in a public server I'm sure I would love to drop by sometime.

Cheers.
